# Generated by Django 3.1.2 on 2020-12-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('userhistory', '0002_auto_20201203_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
