# Generated by Django 3.1.2 on 2020-11-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
