# Generated by Django 3.1.2 on 2020-11-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
