# Generated by Django 3.1.2 on 2020-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20201111_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='slug',
            field=models.SlugField(max_length=125, unique=True),
        ),
    ]
