# Generated by Django 3.1.2 on 2020-12-02 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=15)),
                ('captured', models.DateTimeField()),
                ('received', models.DateTimeField()),
                ('missed', models.DateTimeField()),
                ('stored', models.DateTimeField()),
                ('deceased', models.DateTimeField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
