# Generated by Django 3.1.2 on 2020-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captured',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='deceased',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='missed',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='received',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='stored',
            field=models.DateTimeField(blank=True),
        ),
    ]
