# Generated by Django 3.1.2 on 2020-12-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20201202_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
