# Generated by Django 3.1.2 on 2020-12-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
